name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: cachix/install-nix-action@v30
      - uses: actions/checkout@v4
      - run: nix build
      - uses: actions/upload-artifact@v4
        with:
          name: nix-in-actions
          path: result/bin/nix-in-actions
